server:
  port: 8090
spring:
  application:
    name: olp-courses
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://olp-postgres:5432/olp
    username: peter
    password: enter123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    cache:
      type: redis
  data:
    redis:
      host: redis-container
      port: 6379
  kafka:
    bootstrap-servers: notifications:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

redis:
  host: redis-container
  port: 6379
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
management: 
  endpoints:
    web:
      exposure:
        include: '*'